hostname: localhost

registry:
  host: localhost
  user: admin
  password: admin

db:
  type: None
  # required if db.type is Pod
  pod:
    user: rushhour
    password: rushhour
    database: rushhour
  # required if db.type is External
  external:
    host: localhost
    port: 3306
    user: rushhour
    password: rushhour
    database: rushhour

app:
  baseurl: "http://localhost"
  cookie: ""
  admin_username: admin@example.com
  admin_password: admin
  salt: ""
  state: ""
  key: _16byte_len_str_
  google_client: ""
  google_secret: ""
  twitter_token: ""
  twitter_secret: ""
  github_client: ""
  github_secret: ""

tls: 
  enabled: false
  # required if tls.enabled is true
  cert: |-  
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  key: |-
    -----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----

pv:
  enabled: false
  # required if pv.enabled is true
  storageClassName: ""
  capacity: "10Gi"

# resourcesDB is the limitation of resource for the database.
resourcesDB:
  requests:
    cpu: 100m
    memory: 100M
  limits:
    cpu: 1000m
    memory: 2048M

# resourcesApp is the limitation of resource for application.
resourcesApp:
  requests:
    cpu: 100m
    memory: 100M
  limits:
    cpu: 5000m
    memory: 4096M