apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
      annotations:
        timestamp: {{ date "2006/01/02T15:04:05" .Release.Time | quote }}
    spec:
      containers:
        - name: app
          image: {{ .Values.docker.registry }}/rushhour
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Tokyo
            - name: baseurl
              value: https://{{ .Values.hostname }}
            - name: persist
              value: {{ .Values.secret.db_enabled | quote }}
            {{- if .Values.secret.db_enabled }}
            - name: db_spec
              value: {{ .Values.secret.db_user }}:{{ .Values.secret.db_password }}@tcp({{ .Release.Name }}-db:3306)/{{ .Values.secret.db_database }}{{ .Values.secret.db_args }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-app-secret
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: storage
              mountPath: /rushhour/logs
              subPath: {{ .Release.Name }}-app/logs
          resources:
            {{- toYaml .Values.resourcesApp | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
      imagePullSecrets:
        - name: {{ .Release.Name }}-regcred
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-storage-claim