apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-doc
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-doc
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-doc
      annotations:
        timestamp: {{ date "2006/01/02T15:04:05" .Release.Time | quote }}
    spec:
      containers:
        - name: swagger
          image: {{ .Values.registry.host }}/rushhourswagger
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: BASE_URL
              value: /doc/api
        - name: spec
          image: {{ .Values.registry.host }}/rushhourspec
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: doc-spec
              mountPath: /etc/nginx/conf.d
      imagePullSecrets:
        - name: {{ .Release.Name }}-regcred
      volumes:
        - name: doc-spec
          configMap:
            name: {{ .Release.Name }}-doc-spec