kind: Endpoints
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-storage
  namespace: {{ .Release.Namespace }}
subsets:
  {{- range .Values.endpointGluster }}
  - addresses:
      - ip: {{ . | quote }}
    ports:
      - port: 1
  {{- end }}