apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /doc/api
            backend:
              serviceName: {{ .Release.Name }}-doc
              servicePort: 8080
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-app
              servicePort: 9000
  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: {{ .Release.Name }}-tls