apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Release.Name }}-regcred
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" .Values.registry }}