apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Release.Name }}-tls
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: |
    {{ .Values.tlsCert | b64enc }}
  tls.key: |
    {{ .Values.tlsKey | b64enc }}