apiVersion: v1
kind: Secret
type: Opaque
metadata: 
  name: {{ .Release.Name }}-app-secret
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ printf "%v" $value | b64enc }}
  {{- end }}