{{- if eq .Values.db.type "Pod" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata: 
  name: {{ .Release.Name }}-db-auth
  namespace: {{ .Release.Namespace }}
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.db.pod.password | b64enc }}
  MYSQL_DATABASE: {{ .Values.db.pod.database | b64enc }}
  MYSQL_USER: {{ .Values.db.pod.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.db.pod.password | b64enc }}
{{- end -}}