apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-doc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-doc
  ports:
    - name: {{ .Release.Name }}-doc
      port: 8080